const food = require('public/papa_shop/food.jpg')

module.exports = {
  papa_menu: {
    combo: [
      { name: '雪花鸡柳饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 12,
        img: food,
        number: 0,
      },
      { name: '新奥尔良鸡排饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 13,
        img: food,
        number: 0,
      },
      { name: '香菇滑鸡饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 13,
        img: food,
        number: 0,
      },
      { name: '山贼烤猪排饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '香辣鸡排饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '奥尔良鸡翅饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '劲脆鸡扒饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '咖喱鸡盖浇饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '盐酥鸡块饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
      { name: '黑椒牛柳饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 18,
        img: food,
        number: 0,
      },
      { name: '香烧鸡排饭',
        describe: '啪啪脆，最好吃的小吃店',
        price: 15,
        img: food,
        number: 0,
      },
    ],
    snacks: [
      { name: '薯条(小)',
        describe: '啪啪脆，最好吃的小吃店',
        price: 6,
        img: food,
        number: 0,
      },
      { name: '薯条(大)',
        describe: '啪啪脆，最好吃的小吃店',
        price: 8,
        img: food,
        number: 0,
      },
      { name: '鸡米花',
        describe: '啪啪脆，最好吃的小吃店',
        price: 8,
        img: food,
        number: 0,
      },
      { name: '那么大鸡排',
        describe: '啪啪脆，最好吃的小吃店',
        price: 9,
        img: food,
        number: 0,
      },
      { name: '雪花鸡柳',
        describe: '啪啪脆，最好吃的小吃店',
        price: 8,
        img: food,
        number: 0,
      },
      { name: '蟹柳(5条装)',
        describe: '啪啪脆，最好吃的小吃店',
        price: 5,
        img: food,
        number: 0,
      },
      { name: '奥尔良鸡翅',
        describe: '啪啪脆，最好吃的小吃店',
        price: 6,
        img: food,
        number: 0,
      },
    ],
    beverage: [
      { name: '可乐',
        describe: '啪啪脆，最好吃的小吃店',
        price: 3,
        img: food,
        number: 0,
      },
      { name: '雪碧',
        describe: '啪啪脆，最好吃的小吃店',
        price: 3,
        img: food,
        number: 0,
      },
      { name: '加多宝',
        describe: '啪啪脆，最好吃的小吃店',
        price: 4,
        img: food,
        number: 0,
      },
    ],
  },
}
